from typing import List, Literal, Optional
from pydantic import BaseModel, Field
from app.models.token import DataScope


class AgentAPlan(BaseModel):
    """
    Structured reasoning output generated by Agent A (Coordinator).
    """
    task_type: Literal["financial_analysis_task", "single_customer_audit"] = Field(
        default="financial_analysis_task",
        description="The recognized task or policy identifier"
    )
    customer_id: str = Field(
        ...,
        description="The target customer identifier extracted from the user prompt (e.g. CUST-101)"
    )
    delegation_target: Literal["agent_b"] = Field(
        default="agent_b",
        description="The downstream agent receiving the initial delegation token"
    )
    requested_scope: Literal["financials:read:all", "financials:read:summary", "financials:read:metrics"] = Field(
        default="financials:read:all",
        description="The proposed operational scope requested for Agent B"
    )
    requested_data_scope: DataScope = Field(
        ...,
        description="The proposed customer boundary constraint (e.g. customer_ids: ['CUST-101'])"
    )
    reasoning_summary: str = Field(
        ...,
        description="Brief natural-language summary of Agent A's planning rationale"
    )


class AgentBPlan(BaseModel):
    """
    Structured reasoning output generated by Agent B (Planner).
    """
    customer_id: str = Field(
        ...,
        description="The target customer identifier to analyze"
    )
    delegation_target: Literal["agent_c"] = Field(
        default="agent_c",
        description="The worker agent executing the governed tool"
    )
    requested_scope: Literal["financials:read:summary", "financials:read:metrics", "financials:read:all"] = Field(
        default="financials:read:summary",
        description="The proposed narrow child scope for Agent C"
    )
    requested_data_scope: DataScope = Field(
        ...,
        description="The proposed child customer boundary constraint (must be subset of parent)"
    )
    reasoning_summary: str = Field(
        ...,
        description="Brief natural-language summary of Agent B's sub-task decomposition"
    )


class AgentCToolRequest(BaseModel):
    """
    Structured tool action output generated by Agent C (Worker).
    """
    operation: Literal[
        "READ_FINANCIALS",
        "READ_SUMMARY",
        "READ_METRICS",
        "WRITE_RECORD"
    ] = Field(
        default="READ_SUMMARY",
        description="The proposed financial operation to execute via the Governor Tool Gateway"
    )
    resource: Literal["customer_financials"] = Field(
        default="customer_financials",
        description="Target protected resource domain"
    )
    customer_id: str = Field(
        ...,
        description="Target customer identifier for the tool execution"
    )
    reasoning_summary: str = Field(
        ...,
        description="Brief natural-language explanation of why this financial operation is required"
    )


class LLMExecutionMetadata(BaseModel):
    """
    Safe observability metadata capturing LLM request performance and status.
    """
    model: str
    duration_ms: float
    success: bool
    error_type: Optional[str] = None
    retry_count: int = 0
